### ISSUE TITLE
Problem with figlet dependency

### ISSUE THREAD

**Issue by fernandoguedes** [acifani/soccer-go#10]
First, thank you for the nice project.

Well, I have a issue with `figlet` dependency:

```
➜ fguedes@notebook  ~/Work/github.com/fernandoguedes/soccer-go git:(master) ✗ node lib/index.js 
? Choose a competition 1. Bundesliga
? Choose a function Matchday
(node:22503) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/fguedes/Work/github.com/fernandoguedes/soccer-go/node_modules/figlet/lib/../fonts/slant.flf'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at Function.figlet.loadFontSync (/home/fguedes/Work/github.com/fernandoguedes/soccer-go/node_modules/figlet/lib/node-figlet.js:38:23)
    at Function.me.textSync (/home/fguedes/Work/github.com/fernandoguedes/soccer-go/node_modules/figlet/lib/figlet.js:732:43)
    at Object.<anonymous> (/home/fguedes/Work/github.com/fernandoguedes/soccer-go/lib/commands/fixtures.js:17:32)
    at Generator.next (<anonymous>)
    at /home/fguedes/Work/github.com/fernandoguedes/soccer-go/lib/commands/fixtures.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/fguedes/Work/github.com/fernandoguedes/soccer-go/lib/commands/fixtures.js:3:12)
    at Object.exports.printMatchday (/home/fguedes/Work/github.com/fernandoguedes/soccer-go/lib/commands/fixtures.js:15:41)
(node:22503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22503) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I removed the font param from the `src/commands/fixtures.ts:9` and `src/commands/standings.ts:7` and works nice. I can't found the related issue in `figlet` repository.

**Comment by fernandoguedes** [comment]
Regular installing (`npm i soccer-go`), same error: 

```
➜ fguedes@notebook  /tmp/o  ./node_modules/.bin/soccer-go
? Choose a competition 3. Bundesliga
? Choose a function Matchday
(node:26018) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/tmp/o/node_modules/figlet/lib/../fonts/slant.flf'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at Function.figlet.loadFontSync (/tmp/o/node_modules/figlet/lib/node-figlet.js:38:23)
    at Function.me.textSync (/tmp/o/node_modules/figlet/lib/figlet.js:732:43)
    at Object.<anonymous> (/tmp/o/node_modules/soccer-go/lib/commands/fixtures.js:17:32)
    at Generator.next (<anonymous>)
    at /tmp/o/node_modules/soccer-go/lib/commands/fixtures.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/o/node_modules/soccer-go/lib/commands/fixtures.js:3:12)
    at Object.exports.printMatchday (/tmp/o/node_modules/soccer-go/lib/commands/fixtures.js:15:41)
(node:26018) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26018) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by acifani** [comment]
Nice catch, I will take a look at it tomorrow (midnight here)!

**Comment by acifani** [comment]
Can you try changing the font to "Slant" (uppercase) and see if it fixes the issue for you?

**Comment by fernandoguedes** [comment]
I replaced the name of font and opened PR, the little fix works. Thanks.

**Comment by acifani** [comment]
Will merge to master shortly, thanks again!
